### ISSUE TITLE
Add support for knurling

### ISSUE THREAD

**Issue by pierreporte** [martinproks/cosmeticthread3d#17]
In CAD, knurls are similar to threads in every aspect: the precise 3D representation need intensive computation and they appear in a simpler form in the drawings. Cosmetic threads are a solution. Cosmetic knurls could be a solution too.

There are several standards: DIN 82 and ISO 13444 in the metric world.

The most used are the axial and crossed 30° types. The depth can vary a lot but this should be left for the drawing.

In niche industries like horology, not only cylinders and planar surfaces are knurled: toroidal (convex and concave) and conical surfaces can be knurled as well. Knurling rollers are sold in a wide variety of shapes.

![image](https://github.com/martinproks/cosmeticthread3d/assets/2029853/29f6aa99-068c-4b5b-8d72-739d693649ca)

**Comment by martinproks** [comment]
Hi,

Knurling is not a thread. It should be separate tools. Yeas the approach could be similar most probably, but as separate tool later.

First Cosmetic Threads 3D.
