### ISSUE TITLE
Part & PartDesign attachement helper are inconsistent

### ISSUE THREAD

**Issue by pierreporte** [martinproks/cosmeticthread3d#32]
Consistency is very important in UX. Both the cone and LCS are fine but it should be the same thing for both implementations so that the user knows that is is the same operation. I would suggest keeping the cone or showing some sort of arrow.

**Comment by martinproks** [comment]
I know. I want to have cone/arrow as in Part, it is perfect solution I think. But it is not as easy in PartDesign as in Part. I'm stuck on it for 5 days... So i decide to public it just for now by LCS +Z axis...

**Comment by martinproks** [comment]
Hi,

Try this version please. The helper has been changed in Part and PartDesign to the same visual look.
It is based on Draft.makeWire().

![arrow-DraftWire](https://github.com/martinproks/cosmeticthread3d/assets/153991448/6ad8629e-6ac9-48da-9452-29b559d2bde0)

**Comment by pierreporte** [comment]
It works perfectly. Let’s hope that https://github.com/FreeCAD/FreeCAD/issues/11214 is fixed sooner than later to have something better than a real object in the tree.

I tried with a large thread (by default the cylinder diameter is 20 mm). The object would be more visible if its size depended on the selected circle diameter.

**Comment by martinproks** [comment]
> I tried with a large thread (by default the cylinder diameter is 20 mm). The object would be more visible if its size depended on the selected circle diameter.

Did You try Apply button?
![apply](https://github.com/martinproks/cosmeticthread3d/assets/153991448/e0c892fc-8cee-4cad-afd1-21ea8575f17e)
(edit citation)

**Comment by martinproks** [comment]
> It works perfectly. Let’s hope that [FreeCAD/FreeCAD#11214](https://github.com/FreeCAD/FreeCAD/issues/11214) is fixed sooner than later to have something better than a real object in the tree.

In the case of Pads or Pockets, the situation is different. At the beginning You have sketch, you can "guess" direction and value and this could be presented as ghost geometry. In the case of champfers of blends You have value and You are selecting edges to apply the value. It could be calculated ghost champfer or blend quit well too (usually - if the values are in reasonable relation to faces).

But in the case of thread at the beginning You have to attach to some hole/rod. From the selected edge guess thread type, major diameter and length and at this moment You can have ghost feature. But in the attachment moment You have nothing. I can create directly the thread feature (in the 0,0,0 and direction 0,0,1 with some random/small parameter). At the other hand till You have complete attachment and select at least approximately correct values, the ghost feature is totally misleading. The direction arrow is better solution in the first moment I think.

You can try it actually. You can create non attached default thread from python console (follow doc//How-to-use-it-from-python-console.html). It creates non attached thread with default parameters in 0,0,0 with direction 0,0,1 and then You can manually attache it. Try it on small threads (M2), "normal threads" (M8) and big threads (M100).

**Comment by pierreporte** [comment]
Indeed, the Apply button does the job. Since it works without it, I didn’t even try. The thing is, the helper is at the right place once the concentric entry is selected, so it already knows some information about the circular edge.

**Comment by martinproks** [comment]
Well for now, I'm closing this issue as solved.

Question/request to apply ghost thread in the attachment phase instead of direction arrow is another issue to discuss and may be  enhancement.
