### ISSUE TITLE
PartDesign theads change the display style of the part

### ISSUE THREAD

**Issue by pierreporte** [martinproks/cosmeticthread3d#34]
How to reproduce:

1. Create a part using PartDesign with a display style other than Shaded.
2. Create a PartDesign thread on it.
3. The part now has the Shaded style.

This is because the part takes the style of the thread. You can’t have a different style for both. This is why the helix can’t be shown like with the Part implementation.

**Comment by martinproks** [comment]
OK, I understand problem now (I hope)... Display mode... I have to get display mode from BaseFeature and apply it to the new one... The complexity of this 'small and easy tool' still increases...

**Comment by martinproks** [comment]
Hi,
Please test it and let me know please.
It should be fine now. At least it seems to me it works...

**Comment by pierreporte** [comment]
It doesn’t work for me. The thread object is created, but outside of the body and empty, while the ThreadOrientation is still there. There is a traceback in the report view:

```
21:49:44  pyException: Traceback (most recent call last):
  File "/tmp/.mount_FreeCAi3hTLd/usr/Mod/Part/AttachmentEditor/TaskAttachmentEditor.py", line 330, in accept
    self.callback_OK()
  File "/home/thomas/.local/share/FreeCAD/Mod/CosmeticThread3D/cosmeticthread3d_Gui.py", line 1709, in eA_ok
    obj = ct3d_pd.external_pd0('CosmeticThread3DExternal', ct3d_prms)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/.local/share/FreeCAD/Mod/CosmeticThread3D/cosmeticthread3d_partdesign.py", line 484, in external_pd0
    obj.ViewObject.ShapeColor=body.ViewObject.ShapeColor
    ^^^^^^^^^^^^^^^^^^^^^^^^^
<class 'AttributeError'>: 'PartDesignGui.ViewProvider' object has no attribute 'ShapeColor'
```

FreeCAD version:

```
OS: Ubuntu 23.10 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36807 (Git) AppImage
Build type: Release
Branch: main
Hash: cc96f2718e139d670e08c4226bdea9955a102ed6
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: French/France (fr_FR)
Installed mods: 
  * BillOfMaterials-WB 0.0.7
  * CosmeticThread3D
  * Curves 0.6.29
  * CurvedShapes 1.0.8
  * sheetmetal 0.4.6
  * OpenDark 2023.12.17
  * OpenLight 2023.12.17

```

**Comment by martinproks** [comment]
I'm working on it.
Apparently I do not understand well to ViewProvider, I have to learn more, it takes some time...

**Comment by martinproks** [comment]
Second try to fix it. Try it please. It should work now.

**Comment by pierreporte** [comment]
It has been solved.
